# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/devin/final_project/final_project.srcs/sources_1/ip/bcm/bcm.xci
# IP: The module: 'bcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/final_project/final_project.srcs/sources_1/ip/bcm/bcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/devin/final_project/final_project.srcs/sources_1/ip/bcm/bcm.xci
# IP: The module: 'bcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/final_project/final_project.srcs/sources_1/ip/bcm/bcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
