# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/devin/final_project/final_project.srcs/sources_1/ip/fingerprint_rom/fingerprint_rom.xci
# IP: The module: 'fingerprint_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/final_project/final_project.srcs/sources_1/ip/fingerprint_rom/fingerprint_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fingerprint_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/devin/final_project/final_project.srcs/sources_1/ip/fingerprint_rom/fingerprint_rom.xci
# IP: The module: 'fingerprint_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/devin/final_project/final_project.srcs/sources_1/ip/fingerprint_rom/fingerprint_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fingerprint_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
