# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/nexys4_ddr_lab3.xdc

# IP: ip/image_rom/image_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rom || ORIG_REF_NAME==image_rom} -quiet] -quiet
