# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/devin/final_project/final_project.cache/wt [current_project]
set_property parent.project_path C:/Users/devin/final_project/final_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/devin/final_project/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/devin/Images_6111/fingerprint.coe
add_files C:/Users/devin/Images_6111/fingerprint_color_map_blue.coe
add_files C:/Users/devin/Images_6111/fingerprint_color_map_red.coe
add_files C:/Users/devin/Images_6111/fingerprint_color_map_green.coe
add_files c:/Users/devin/Downloads/ds_color_map_red.coe
add_files c:/Users/devin/Downloads/ds_color_map_green.coe
add_files c:/Users/devin/Downloads/ds_color_map_blue.coe
add_files c:/Users/devin/Downloads/ds_image_emma.coe
read_verilog -library xil_defaultlib -sv {
  C:/Users/devin/final_project/final_project.srcs/sources_1/imports/new/blob.sv
  C:/Users/devin/final_project/final_project.srcs/sources_1/imports/Downloads/debounce.sv
  C:/Users/devin/final_project/final_project.srcs/sources_1/imports/new/picture_blob.sv
  C:/Users/devin/final_project/final_project.srcs/sources_1/imports/Downloads/picture_blob_emma.sv
  C:/Users/devin/final_project/final_project.srcs/sources_1/new/random_num.sv
  C:/Users/devin/final_project/final_project.srcs/sources_1/imports/Downloads/timer.sv
  C:/Users/devin/final_project/final_project.srcs/sources_1/new/top_level.sv
}
read_verilog -library xil_defaultlib C:/Users/devin/final_project/final_project.srcs/sources_1/imports/Downloads/clk_wiz_lab3.v
read_vhdl -library xil_defaultlib {
  C:/Users/devin/final_project/final_project.srcs/sources_1/imports/Downloads/TWICtl.vhd
  C:/Users/devin/final_project/final_project.srcs/sources_1/imports/Downloads/TempSensorCtl.vhd
}
read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/image_rom/image_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/image_rom/image_rom_ooc.xdc]

read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/fingerprint_rom/fingerprint_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/fingerprint_rom/fingerprint_rom_ooc.xdc]

read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/blue_fing/blue_fing.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/blue_fing/blue_fing_ooc.xdc]

read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/red_fing/red_fing.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/red_fing/red_fing_ooc.xdc]

read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/green_fing/green_fing.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/green_fing/green_fing_ooc.xdc]

read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/red/red.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/red/red_ooc.xdc]

read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/gcm/gcm.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/gcm/gcm_ooc.xdc]

read_ip -quiet C:/Users/devin/final_project/final_project.srcs/sources_1/ip/bcm/bcm.xci
set_property used_in_implementation false [get_files -all c:/Users/devin/final_project/final_project.srcs/sources_1/ip/bcm/bcm_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/devin/final_project/final_project.srcs/constrs_1/imports/Downloads/nexys4_ddr_lab3.xdc
set_property used_in_implementation false [get_files C:/Users/devin/final_project/final_project.srcs/constrs_1/imports/Downloads/nexys4_ddr_lab3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
